repo_cloneall should clone into the mi_home/repos directory

diff --git a/bin/repo_cloneall b/bin/repo_cloneall
--- a/bin/repo_cloneall
+++ b/bin/repo_cloneall
@@ -24,5 +24,5 @@ for i in ${mi_reposlist[@]}; do
 	[[ "${i}" =~ ^# ]] && continue;
 	[[ -d "${i}" ]] && echo "* ${i} already exists, skipping." && continue;
 	echo "* Cloning ${mi_gitserver}/$i into ${i}..";
-	git clone ${mi_gitserver}/${i}.git || fail "* ERROR - Couldn't clone ${mi_gitserver}/${i}.git.";
+	git clone ${mi_gitserver}/${i}.git "${mi_home}/repos/${i}" || fail "* ERROR - Couldn't clone ${mi_gitserver}/${i}.git.";
 done
